import Head from 'next/head'
import About from '../components/About'
import Contact from '../components/Contact'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Navbar from '../components/Navbar'
import TariffPage from '../components/TariffPage'
import { useState, useEffect } from "react";
import PageLoader from "../components/PageLoader";

export default function Home() {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(false);
  }, []);

  return (
    <div>
      {loading ? (
        <PageLoader />
      ) : (
        <div className="container">
          <Head> <title>Create Next App</title> <meta name="description" content="Generated by create next app" /> <meta name="viewport" content="width=device-width, initial-scale=1" /> <link rel="icon" href="/favicon.ico" /> </Head>
          <Navbar />
          <Header />
          <About />
          <TariffPage />
           <Contact />
            <Footer />
        </div>
      )}
    </div>
  );
}
